### ISSUE TITLE
Require non-cancelable events with "should" or "must" when there are only passive listeners

### ISSUE THREAD

**Issue by zcorpan** [w3c/touch-events#130]
The spec allows non-cancellable events in https://w3c.github.io/touch-events/#cancelability 

> In particular, a user agent may generate only uncancelable touch events when it [observes that there are no non-passive listeners](https://dom.spec.whatwg.org/#observing-event-listeners) for the event.

Why is this is only a "may", and not a "must" or at least "should"?

(This came up in https://github.com/web-platform-tests/wpt/issues/34464#issuecomment-1168496273 )

**Comment by patrickhlauke** [comment]
i believe some of the cautious language (should and may, rather than must) was a result of the history of this spec (and the fact that further development is only a CG draft report), which more or less retrospectively documented behavior done by Webkit (coupled with the fact that there was initially a bit of a PAG saber-rattling over the original 1.0 spec itself).

happy to go over the spec and make it more forceful where necessary.
