### ISSUE TITLE
Length of changedTouches list during a touchstart event

### ISSUE THREAD

**Issue by AFBarstow** [w3c/touch-events#34]
The [spec says](http://w3c.github.io/touch-events/#widl-TouchEvent-changedTouches) the following regarding changed changedTouches list and touchstart events:

[[
For the touchstart event this must be a list of the touch points that just became active with the current event.
]]

This implies changedTouches can have more than one touch point during touchstart but is that really the case? It seems like during a touchstart event, changedTouches will only have one touch point.

**Comment by RByers** [comment]
In chromium I believe we'll never put two new touches in the same `touchstart` (or `touchend` event) but this is really just due to the API design of the underlying platforms we run on (where each finger comes as a separate event) and our desire not to buffer start/end events at all.  So I see no reason to require separate events (I could imagine doing a small performance optimization to try to merge these).

On iOS however, the underlying API design matches the model of touch events, and sure enough there I can see multiple `changedTouches` in a single `touchstart` or `touchend` event.  [Here's a test page](http://jsbin.com/jikalu).

**Comment by AFBarstow** [comment]
ok; thanks for checking @RByers!
