### ISSUE TITLE
Need tests for ontouch*, the GlobalEventHandlers

### ISSUE THREAD

**Issue by AFBarstow** [w3c/touch-events#44]
This is a placeholder/reminder tests are needed for the 4 ontouch\* global event handlers added to v2.

Another option for tracking this spec's testing issues/bugs/holes would be to create issues within [the test suite repo](https://github.com/w3c/web-platform-tests/tree/master/touch-events). If doing this is preferred, please let me know and I'll close issue and create a new issue in the test repo.

**Comment by RByers** [comment]
Yeah, good point, thanks.  /cc @choniong 
Tracking test issues here makes sense to me (like #27).

**Comment by chong-z** [comment]
I'm not so sure what kind of tests should I add? It seems that touch functional tests are already done in [the test suit repo](https://github.com/w3c/web-platform-tests/tree/master/touch-events) and interface tests are done in [global-interface-listing](https://code.google.com/p/chromium/codesearch#chromium/src/third_party/WebKit/LayoutTests/webexposed/global-interface-listing-expected.txt&sq=package:chromium&l=1031)

**Comment by RByers** [comment]
I don't think there's anything in the web-platform-test repo that specifically looks at or uses the `ontouch*` attributes.  I'd suggest the following:
- make a small update to single-touch-manual.html to try using a couple of these attributes
  - note that we intentionally minimize the number of manual test cases (to make running the tests as easy as possible), so don't add a new test case, just piggy back on the existing one.
  - rather than always use on_event (which is just a silly wrapper around addEventListener AFAICT), you want to write code like `target0.ontouchmove = function onTouchMove(ev) {...` and `window.ontouchend = ...`.  It's probably OK to just convert a couple of the on_event tests to this pattern (so we have a mix of listening styles, covering a few different use cases.
  - please verify these pass on Mobile Safari, Firefox, Chrome and Windows Mobile
- then for exhaustive completeness create a new automated test which just verifies the existence and exact details of the APIs.  Eg:
  - for each name of 'ontouchstart', 'ontouchmove', 'ontouchend' and 'ontouchcancel':
    - for each obj of window, HTMLElement.prototype and SVGElement.prototype:
    - verify "name in obj" is true (this is the simple thing that will pass on all browsers)
    - verify "obj.hasOwnProperty(name)" - this will fail today in some cases on some browsers but should now pass in Chrome.  You could use Object.getOwnPropertyDescriptor (eg. to also verify the attributes are writable) but IMHO that's probably overkill and so unnecessary.  Others may disagree.
  - verify "name in Element.prototype" is false (again this will fail in some browsers, but Edge plans to match Chrome here).

**Comment by chong-z** [comment]
Fixed in https://github.com/w3c/web-platform-tests/pull/2393

**Comment by RByers** [comment]
Thanks!
