### ISSUE TITLE
Remove tests from this repository in favour of wpt.

### ISSUE THREAD

**Issue by Ms2ger** [w3c/touch-events#46]
Also move the existing issues.

**Comment by AFBarstow** [comment]
Yes, w-p-t/touch-events is definitely where all test work should be done. 

Without actually running a diff, I suspect all the tests in https://github.com/w3c/web-platform-tests/tree/master/touch-events are the only tests that should be used and maintained and that most (if not all of) https://github.com/w3c/touch-events/tree/gh-pages/tests can be deleted.

**Comment by AFBarstow** [comment]
@Ms2ger I did some investigating and I think all of https://github.com/w3c/touch-events/tree/gh-pages/tests  can be deleted. That directory was included in GH when the spec was moved from (Hg https://dvcs.w3.org/hg/webevents/file/bca491d2ba3f/test) but there haven't been any changes to it and https://github.com/w3c/web-platform-tests/tree/master/touch-events should be the one and only repo for Touch Events specs.

So, unless I hear otherwise from @mbrubeck @RByers @cynthia @ollipettay, etc. I will go ahead and delete the tests directory (and copy/move the two issues #27 and #44 to w-p-t).

**Comment by RByers** [comment]
Yes the copy here should be removed, thanks!  Sorry I didn't notice this.

I'm less sure about the issues though.  If they're moved, then we can't assign them to people like myself who don't have WPT push access (a known github limitation) and I for one will loose track of work I intend to have someone on my team do.  Maybe that's fine - I'll just rely on redundant bugs / comments in the chromium bug tracker (which I generally do already).

**Comment by AFBarstow** [comment]
@Ms2ger I deleted the tests directory. I think @RByers has a good point re these two issues and they provide a good tracking mechanism for the Touch Events CG. Does Github support an issue being assigned to more than one repo? If not, perhaps we can leave #27 and #44 as is and I'll create two new issues in the w-p-t/touch-events repo that includes links back to these two issues. WDYT?

**Comment by Ms2ger** [comment]
As long as the issues are in wpt and linked both ways, I don't feel strongly about closing the issues here. Thanks!

**Comment by AFBarstow** [comment]
@choniong already added #27 to w-p-t https://github.com/w3c/web-platform-tests/pull/2299 and I just added #44 https://github.com/w3c/web-platform-tests/issues/2375 so closing this.

**Comment by AFBarstow** [comment]
@Ms2ger when you get a chance, please label https://github.com/w3c/web-platform-tests/issues/2375 with touch-events (it appears I can't do that)
